/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || "https://scottwindsor.com",
  generateRobotsTxt: true,
  generateIndexSitemap: false,
  exclude: ["/admin/*", "/api/*"],
  robotsTxtOptions: {
    additionalSitemaps: [],
    policies: [
      { userAgent: "*", allow: "/" },
      { userAgent: "*", disallow: ["/admin", "/api"] },
    ],
  },
  transform: async (config, path) => {
    const priorities = {
      "/": 1.0,
      "/listings": 0.9,
      "/home-value": 0.9,
      "/sell": 0.9,
      "/new-construction": 0.9,
      "/harrison-ohio-real-estate-market": 0.9,
      "/moving-to-harrison-ohio": 0.9,
      "/realtor-harrison-ohio": 0.9,
      "/sell/sell-my-home-harrison-ohio": 0.9,
      "/neighborhoods": 0.8,
      "/about": 0.8,
      "/contact": 0.8,
      "/first-time-buyers": 0.8,
      "/harrison-ohio-schools": 0.8,
      "/homes-for-sale/new-construction-harrison-ohio": 0.8,
      "/first-time-home-buyer-harrison-ohio": 0.8,
      "/harrison-ohio-best-neighborhoods": 0.8,
      "/harrison-ohio-commute-to-cincinnati": 0.8,
      "/open-houses": 0.7,
      "/sold": 0.7,
      "/blog": 0.7,
      "/homes-for-sale/harrison-ohio-under-300000": 0.7,
      "/homes-for-sale/harrison-ohio-under-200000": 0.7,
      "/homes-for-sale/harrison-ohio-under-400000": 0.7,
      "/homes-for-sale/harrison-ohio-3-bedroom": 0.7,
      "/homes-for-sale/harrison-ohio-4-bedroom": 0.7,
      "/homes-for-sale/harrison-ohio-ranch-homes": 0.7,
      "/homes-for-sale/harrison-ohio-condos": 0.7,
      "/homes-for-sale/harrison-ohio-with-acreage": 0.7,
      "/homes-for-sale/harrison-ohio-luxury-homes": 0.7,
      "/homes-for-sale/harrison-ohio-zip-code-45030": 0.7,
      "/homes-for-sale/homes-near-miami-whitewater-forest": 0.7,
      "/homes-for-sale/cleves-ohio": 0.7,
      "/homes-for-sale/north-bend-ohio": 0.7,
      "/homes-for-sale/west-harrison-ohio": 0.7,
      "/homes-for-sale/whitewater-township-ohio": 0.7,
      "/homes-for-sale/new-baltimore-ohio": 0.7,
      "/homes-for-sale/anderson-township-ohio": 0.7,
      "/homes-for-sale/harrison-ohio-investment-property": 0.7,
      "/sell/sell-my-home-cleves-ohio": 0.7,
      "/sell/home-value-harrison-ohio": 0.7,
      "/harrison-ohio-safe-neighborhoods": 0.7,
      "/harrison-ohio-property-taxes": 0.7,
      "/harrison-ohio-open-houses": 0.7,
      "/harrison-ohio-home-buying-process": 0.7,
    };

    return {
      loc: path,
      changefreq: path === "/" ? "daily" : path.startsWith("/blog/") ? "monthly" : "weekly",
      priority: priorities[path] || 0.6,
      lastmod: new Date().toISOString(),
    };
  },
};
